# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raw_types.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='raw_types.proto',
  package='model.detections.raw',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fraw_types.proto\x12\x14model.detections.raw\"%\n\rIntCoordinate\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\'\n\x0f\x46loatCoordinate\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"\\\n\x04\x42\x42ox\x12\x35\n\x08top_left\x18\x01 \x01(\x0b\x32#.model.detections.raw.IntCoordinate\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\"Z\n\x0cOffsetVector\x12\x37\n\x08position\x18\x01 \x01(\x0b\x32%.model.detections.raw.FloatCoordinate\x12\x11\n\tmagnitude\x18\x02 \x01(\x02\"\x86\x03\n\rHandDetection\x12(\n\x04\x62\x62ox\x18\x01 \x01(\x0b\x32\x1a.model.detections.raw.BBox\x12\r\n\x05score\x18\x02 \x01(\x02\x12<\n\x05state\x18\x03 \x01(\x0e\x32-.model.detections.raw.HandDetection.HandState\x12\x32\n\x06offset\x18\x04 \x01(\x0b\x32\".model.detections.raw.OffsetVector\x12:\n\x04side\x18\x05 \x01(\x0e\x32,.model.detections.raw.HandDetection.HandSide\"m\n\tHandState\x12\x0e\n\nNO_CONTACT\x10\x00\x12\x10\n\x0cSELF_CONTACT\x10\x01\x12\x12\n\x0e\x41NOTHER_PERSON\x10\x02\x12\x13\n\x0fPORTABLE_OBJECT\x10\x03\x12\x15\n\x11STATIONARY_OBJECT\x10\x04\"\x1f\n\x08HandSide\x12\x08\n\x04LEFT\x10\x00\x12\t\n\x05RIGHT\x10\x01\"J\n\x0fObjectDetection\x12(\n\x04\x62\x62ox\x18\x01 \x01(\x0b\x32\x1a.model.detections.raw.BBox\x12\r\n\x05score\x18\x02 \x01(\x02\"\xa0\x01\n\nDetections\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\x14\n\x0c\x66rame_number\x18\x02 \x01(\x05\x12\x32\n\x05hands\x18\x03 \x03(\x0b\x32#.model.detections.raw.HandDetection\x12\x36\n\x07objects\x18\x04 \x03(\x0b\x32%.model.detections.raw.ObjectDetectionb\x06proto3'
)



_HANDDETECTION_HANDSTATE = _descriptor.EnumDescriptor(
  name='HandState',
  full_name='model.detections.raw.HandDetection.HandState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_CONTACT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SELF_CONTACT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ANOTHER_PERSON', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PORTABLE_OBJECT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATIONARY_OBJECT', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=556,
  serialized_end=665,
)
_sym_db.RegisterEnumDescriptor(_HANDDETECTION_HANDSTATE)

_HANDDETECTION_HANDSIDE = _descriptor.EnumDescriptor(
  name='HandSide',
  full_name='model.detections.raw.HandDetection.HandSide',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=667,
  serialized_end=698,
)
_sym_db.RegisterEnumDescriptor(_HANDDETECTION_HANDSIDE)


_INTCOORDINATE = _descriptor.Descriptor(
  name='IntCoordinate',
  full_name='model.detections.raw.IntCoordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='model.detections.raw.IntCoordinate.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='model.detections.raw.IntCoordinate.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=78,
)


_FLOATCOORDINATE = _descriptor.Descriptor(
  name='FloatCoordinate',
  full_name='model.detections.raw.FloatCoordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='model.detections.raw.FloatCoordinate.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='model.detections.raw.FloatCoordinate.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=119,
)


_BBOX = _descriptor.Descriptor(
  name='BBox',
  full_name='model.detections.raw.BBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='top_left', full_name='model.detections.raw.BBox.top_left', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='model.detections.raw.BBox.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='model.detections.raw.BBox.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=213,
)


_OFFSETVECTOR = _descriptor.Descriptor(
  name='OffsetVector',
  full_name='model.detections.raw.OffsetVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='model.detections.raw.OffsetVector.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='magnitude', full_name='model.detections.raw.OffsetVector.magnitude', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=305,
)


_HANDDETECTION = _descriptor.Descriptor(
  name='HandDetection',
  full_name='model.detections.raw.HandDetection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bbox', full_name='model.detections.raw.HandDetection.bbox', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='model.detections.raw.HandDetection.score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='model.detections.raw.HandDetection.state', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='offset', full_name='model.detections.raw.HandDetection.offset', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='side', full_name='model.detections.raw.HandDetection.side', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HANDDETECTION_HANDSTATE,
    _HANDDETECTION_HANDSIDE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=698,
)


_OBJECTDETECTION = _descriptor.Descriptor(
  name='ObjectDetection',
  full_name='model.detections.raw.ObjectDetection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bbox', full_name='model.detections.raw.ObjectDetection.bbox', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='model.detections.raw.ObjectDetection.score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=700,
  serialized_end=774,
)


_DETECTIONS = _descriptor.Descriptor(
  name='Detections',
  full_name='model.detections.raw.Detections',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_id', full_name='model.detections.raw.Detections.video_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_number', full_name='model.detections.raw.Detections.frame_number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hands', full_name='model.detections.raw.Detections.hands', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='objects', full_name='model.detections.raw.Detections.objects', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=777,
  serialized_end=937,
)

_BBOX.fields_by_name['top_left'].message_type = _INTCOORDINATE
_OFFSETVECTOR.fields_by_name['position'].message_type = _FLOATCOORDINATE
_HANDDETECTION.fields_by_name['bbox'].message_type = _BBOX
_HANDDETECTION.fields_by_name['state'].enum_type = _HANDDETECTION_HANDSTATE
_HANDDETECTION.fields_by_name['offset'].message_type = _OFFSETVECTOR
_HANDDETECTION.fields_by_name['side'].enum_type = _HANDDETECTION_HANDSIDE
_HANDDETECTION_HANDSTATE.containing_type = _HANDDETECTION
_HANDDETECTION_HANDSIDE.containing_type = _HANDDETECTION
_OBJECTDETECTION.fields_by_name['bbox'].message_type = _BBOX
_DETECTIONS.fields_by_name['hands'].message_type = _HANDDETECTION
_DETECTIONS.fields_by_name['objects'].message_type = _OBJECTDETECTION
DESCRIPTOR.message_types_by_name['IntCoordinate'] = _INTCOORDINATE
DESCRIPTOR.message_types_by_name['FloatCoordinate'] = _FLOATCOORDINATE
DESCRIPTOR.message_types_by_name['BBox'] = _BBOX
DESCRIPTOR.message_types_by_name['OffsetVector'] = _OFFSETVECTOR
DESCRIPTOR.message_types_by_name['HandDetection'] = _HANDDETECTION
DESCRIPTOR.message_types_by_name['ObjectDetection'] = _OBJECTDETECTION
DESCRIPTOR.message_types_by_name['Detections'] = _DETECTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IntCoordinate = _reflection.GeneratedProtocolMessageType('IntCoordinate', (_message.Message,), {
  'DESCRIPTOR' : _INTCOORDINATE,
  '__module__' : 'raw_types_pb2'
  # @@protoc_insertion_point(class_scope:model.detections.raw.IntCoordinate)
  })
_sym_db.RegisterMessage(IntCoordinate)

FloatCoordinate = _reflection.GeneratedProtocolMessageType('FloatCoordinate', (_message.Message,), {
  'DESCRIPTOR' : _FLOATCOORDINATE,
  '__module__' : 'raw_types_pb2'
  # @@protoc_insertion_point(class_scope:model.detections.raw.FloatCoordinate)
  })
_sym_db.RegisterMessage(FloatCoordinate)

BBox = _reflection.GeneratedProtocolMessageType('BBox', (_message.Message,), {
  'DESCRIPTOR' : _BBOX,
  '__module__' : 'raw_types_pb2'
  # @@protoc_insertion_point(class_scope:model.detections.raw.BBox)
  })
_sym_db.RegisterMessage(BBox)

OffsetVector = _reflection.GeneratedProtocolMessageType('OffsetVector', (_message.Message,), {
  'DESCRIPTOR' : _OFFSETVECTOR,
  '__module__' : 'raw_types_pb2'
  # @@protoc_insertion_point(class_scope:model.detections.raw.OffsetVector)
  })
_sym_db.RegisterMessage(OffsetVector)

HandDetection = _reflection.GeneratedProtocolMessageType('HandDetection', (_message.Message,), {
  'DESCRIPTOR' : _HANDDETECTION,
  '__module__' : 'raw_types_pb2'
  # @@protoc_insertion_point(class_scope:model.detections.raw.HandDetection)
  })
_sym_db.RegisterMessage(HandDetection)

ObjectDetection = _reflection.GeneratedProtocolMessageType('ObjectDetection', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTDETECTION,
  '__module__' : 'raw_types_pb2'
  # @@protoc_insertion_point(class_scope:model.detections.raw.ObjectDetection)
  })
_sym_db.RegisterMessage(ObjectDetection)

Detections = _reflection.GeneratedProtocolMessageType('Detections', (_message.Message,), {
  'DESCRIPTOR' : _DETECTIONS,
  '__module__' : 'raw_types_pb2'
  # @@protoc_insertion_point(class_scope:model.detections.raw.Detections)
  })
_sym_db.RegisterMessage(Detections)


# @@protoc_insertion_point(module_scope)
